version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: docker/node/DockerFile
    container_name: barberShop-server-email-node
    volumes:
      - .:/home/node/nest
    working_dir: /var/www/api_email/
    restart: always
