version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: docker/php/DockerFile
    container_name: barberShop-servidor-laravel
    restart: always
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./:/var/www
    environment:
      - COMPOSER_HOME=/composer
      - COMPOSER_ALLOW_SUPERUSER=1
      - APP_ENV=local
      - APP_KEY=base64:jxZmj1jJa5IRxS89eLzIsDo0y0zowUQCvXOVYMYjMes=
    depends_on:
      - db
      - redis
    links:
      - db

  nginx:
    image: nginx:latest
    container_name: barberShop-servidor-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d

  redis:
    build:
      context: ./
      dockerfile: docker/redis/DockerFile
    container_name: barberShop-servidor-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  db:
    build:
      context: ./
      dockerfile: docker/db/DockerFile
    container_name: barberShop-servidor-db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  redis:
  db:
